<?php
/*
 * logout.php
 * Logout
 */

session_start();
session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
    <head>
        <meta HTTP-EQUIV="REFRESH" content="2; url=index.php">
        <title>
            Logged out
        </title>
        <link rel="stylesheet" href="styles.css" type="text/css" />
    </head>
    <body>
        <div id="container">
            <?PHP include('header.php'); ?>
            <div id="content">
                <?PHP
                session_unset();
                session_write_close();
                ?>
                <p>Logging out...</p>
            </div>
        </div>
    </body>
</html>